/src/main/java/com/skyscanner/hoenscanner/
    HoenScannerApplication.java
    HoenScannerConfiguration.java
    model/
        Search.java
        SearchResult.java
    resources/
        SearchResource.java
/src/main/resources/
    rental_cars.json
    hotels.json
    config.yml
pom.xml